services:
  - type: web
    name: web-scraper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/api_server_db.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production

  - type: web
    name: web-scraper-frontend
    env: node
    buildCommand: cd svelte-dashboard && npm install && npm run build
    startCommand: cd svelte-dashboard && npx vite preview --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://webscraper-jase.onrender.com/api