name: 'Scraper: West Lindsey Consultations'

on:
  schedule:
    # Run at 6:00 AM UTC daily
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-west-lindsey:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run West Lindsey scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python -m backend.scraper.run_west_lindsey

    - name: Log completion
      run: |
        echo "✅ West Lindsey scraper completed at $(date)"